# numpy clip

In [14]:
import numpy as np
a = np.arange(10); a
np.clip(a, 1, 8);a 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.clip(a, 3, 6, out=a)


array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])

In [ ]:
a = np.arange(10);a 
np.clip(a, [3, 4, 1, 1, 1, 4, 4, 4, 4, 4], 8)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])